### ISSUE TITLE
drainsafe does not allow other sources of cordoning a node

### ISSUE THREAD

**Issue by Michael-Sinz** [awesomenix/drainsafe#1]
With drainsafe running, issuing a kubectl cordon on a node will just uncordon it within seconds.

This prevents other pre-existing systems from maintaining a node for whatever reason they need, including a kubectl drain command in order to remove the node from the system due to scaling needs.

**Comment by awesomenix** [comment]
Thanks for reporting the issue, will work on this soon (sorry was on time-off and didnt check any emails)

Idea is that currently the assumption is that only drainsafe is allowed to cordon/uncordon the nodes (which was the initial version). There are 2 ways to solve this issue

1. Annotate cordon ownership
2. Allow certain nodes to be in manual cordon/uncordon mode by letting clients annotate.

Having 2 would mean to educate everyone doing cordon of nodes which can get annoying. Will go ahead with 1 and tag PR the issue.

**Comment by Michael-Sinz** [comment]
Thank you - that would make things better and allow this to work with other processes such as autoscaling and node maintenance within the cluster.  Our draining has ownership that we annotate on the node when we cordon it such that when we want to uncordon it, it must have this annotation (that is then removed).  I don't know what kubectl drain does but I would guess is that it does not have ownership annotations but then it is doing what kubectl drain does.  The same for autoscaling of nodes.

**Comment by awesomenix** [comment]
Thanks for the explanation @Michael-Sinz I have fixed the bug with commit https://github.com/awesomenix/drainsafe/commit/4a65dc431da67e8106d3a24ba97c9da8fcb59138 and pushed the latest image to quay.io/awesomenix/drainsafe-manager. Just restarting the drainsafe controller should automatically fix this issue.

**Comment by alanjcastonguay** [comment]
Ideally this project would coexist well with https://github.com/weaveworks/kured

**Comment by awesomenix** [comment]
Thanks @alanjcastonguay, Due to some limitations with kured (examples are stuck operations which require manual intervention and unable to honor repair ordering), I am trying to get https://github.com/awesomenix/repairman with https://github.com/weaveworks/kured and along with current project would provide the safest environment for a customer on Azure.
