### ISSUE TITLE
Add support for Windows nodes

### ISSUE THREAD

**Issue by khuedoan** [awesomenix/drainsafe#2]
We have some Windows nodes in our cluster (for reference https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/).

Please add support for Windows container, we can use the following tag in a separate Dockerfile for Windows, but I'm not sure if all of the features will be available for Windows.

```Dockerfile
FROM golang:1.14-windowsservercore as builder
```

**Comment by awesomenix** [comment]
Thanks for reporting the issue, will work on it this week and send out an update to have a separate drainsafe-deployment.yaml for windows nodes. Will test this in AKS cluster.

**Comment by khuedoan** [comment]
Thank you very much :tada:

**Comment by khuedoan** [comment]
FIY I've started working on this, in case you didn't have time to work on this yet. I've created a draft PR (#3), any feedback or guidance is appreciated 😄

**Comment by khuedoan** [comment]
Closing because because I don't have time to work on this since we're not using self managed Kubernetes anymore
